apiVersion: v1
kind: ReplicationController
metadata:
  name: fristrc
spec:
  replicas: 2
  selector:
    app: web
    deployment: prod
  template:
    metadata:
      name: "mypod1"
      labels:
        app: web
        deployment: prod
    spec:
      containers:
      - name: "container"
        image: "httpd"
