apiVersion: v1
kind: ReplicationController
metadata:
  name: pracrc
spec:
  replicas: 3
  selector:
    app: web
    deployment: prod
  template:
    metadata:
      name: "pracpod"
      labels:
        app: web
        deployment: prod
    spec:
      containers:
      - name: "praccontainer"
        image: "vimal13/apache-webserver-php"
        ports:
          - containerPort: 80
            name: http-web-svc

---

apiVersion: v1
kind: Service
metadata:
  name: pracservice

spec:
  type: NodePort
  selector:
    app: "web"
  ports:
   - port: 80
     targetPort: http-web-svc
     nodePort: 30000
  
